### ISSUE TITLE
Most methods only work if underlying data is an array

### ISSUE THREAD

**Issue by dducro** [ecrmnn/collect.js#151]
Most methods (like "where") only work on array data.

Take this as an example:

```
let filtered = collect([
    { test: 1 },
    { test: 2 }
]).where('test', 2);
```

`filtered` equals a collection with just the second object.
However the following throws an exception.

```
let filtered = collect([
    { test: 1 },
    { test: 2 }
]).keyBy('test').where('test', 2);
```

This is because by calling `keyBy()` the underlying array is converted to an object.

I understand this is done, however I also expect methods like `where()` are still usable.

Is it an option to convert the items property to an array (if it is an object) in the affected methods to preserve expected behavior?
Beside this keys also need the be preserved, so just converting it to an array is not a complete solution..

**Comment by ecrmnn** [comment]
This should work. It is possible with Laravel collections. I think it’s as simple as looping through the objects properties where the value is an array of objects. I’ll have a closer look at what Laravel are doing.

**Comment by dducro** [comment]
Thanks for your response!
That's true and also what's happening.
However, after calling `keyBy()` the `items` array isn't an array anymore, but it is changed to an object.
Therefor calling `where` will result in the following: `this.items.filter is not a function`

**Comment by Helfull** [comment]
i can confirm the problem here.

in laravel we just need to handle arrays because all collections (hashmap or array) are just arrays and share the same method set.
While in JS we have Objects (hashmap) and Arrays (array,  not keyed) so for every method we need to implement 2 versions array and object iterators.

that was the reason why i started to implement some helper functions [Here](https://github.com/ecrmnn/collect.js/pull/149/commits/5914812be1e0fe3f5f6a80945d55efeea440ac99)
