### ISSUE TITLE
Non-recursive values()

### ISSUE THREAD

**Issue by philippkuehn** [ecrmnn/collect.js#217]
In v4.13.0 the behavior of `values()` changed as intended. However, I think there is a use case for the old behavior. When working with a store like vuex, it's a good practice to store items by a key like this to easily pick an item by its id:

```js
const data = {
  1: {
    id: 1,
    name: 'A New Hope',
    director: {
      name: 'George Lucas',
    },
  },
  2: {
    id: 2,
    name: 'Attack of the Clones',
    director: {
      name: 'George Lucas',
    },
  },
}
```

With `collect(data).values().toArray()` I had easy access to an untouched array of my data. The `values()` function of lodash does the same.

```js
[
  {
    id: 1,
    name: 'A New Hope',
    director: {
      name: 'George Lucas',
    },
  },
  {
    id: 2,
    name: 'Attack of the Clones',
    director: {
      name: 'George Lucas',
    },
  },
]
```

But now I get this:

```js
[
  [
    1,
    "A New Hope",
    [
      "George Lucas"
    ]
  ],
  [
    2,
    "Attack of the Clones",
    [
      "George Lucas"
    ]
  ]
]
```

Is there any other simple way to get the result of the old `values` function? Or maybe you can provide a new function for it? Thanks!

**Comment by ecrmnn** [comment]
Hi @philippkuehn 

Thanks for your feedback.
I was already thinking about changing this, and I've decided to revert this change.
`values()` will no longer be recursive as of `4.15.0`

The change was made so that other use cases would closer resemble how Laravel and PHP does this. Due to associative arrays in PHP its not always easy to choose the right approach for JS.

Anyway, I feel like this is the correct solution.
Sorry for the inconvenience.

**Comment by philippkuehn** [comment]
Thanks!
