### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Mashiane** [ecrmnn/collect.js#274]
Hi there

Can you please help me get clarity on.

Q1. Assuming your collection is defined from an array of objects, how do I get an index of a complete object?

There are some examples that are not clear for example wrap and unwrap? Can you make more clarifying examples that will perhaps show differences between what was originally passed and the output.

**Comment by ecrmnn** [comment]
I'm not completely sure what you are asking.
You can get an item by index with the `get` method.
With collect.js you never _(at least rarely)_ look up something by index, that's kind of the point of the library, to give the developer a better experience iteracting with arrays and objects in JavaScript.
I've put together a few examples for you here 👇
https://runkit.com/embed/5k2djkphs7aw

Wrap will turn an array into a collection. If you pass a collection you will get the collection returned.
Documentation: https://collect.js.org/api/wrap.html
Source: https://github.com/ecrmnn/collect.js/blob/master/src/methods/wrap.js

Unwrap will return all items by calling `all` under the hood if the passed value is a collection.
If it's _not_ a collection the passed value will simply be returned.
Documentation: https://collect.js.org/api/unwrap.html
Source: https://github.com/ecrmnn/collect.js/blob/master/src/methods/unwrap.js

To be fair I've never seen the need for these methods either. I've never used them, but they're implemented because collect.js should adhere to the API of Laravel Collections. The same methods should be available.
