### ISSUE TITLE
mapWithKeys().all() returns type array, when it's actually an object

### ISSUE THREAD

**Issue by BrennerSpear** [ecrmnn/collect.js#304]
```
const contractsCollection = collect(contracts)
const keys = contractsCollection.mapWithKeys((contract) => [contract.address, contract.abi])
const contractToAbiMap = keys.all()
```

`keys.all()` returns type `unknown[]` when it should be returning an object type

**Comment by ecrmnn** [comment]
Thanks for reporting. 
I don’t personally use TypeScript, but would appreciate a pull request 😊

**Comment by BrennerSpear** [comment]
Just put up #306

**Comment by mjsarfatti** [comment]
I know it's been a long time but I'm coming across the same issue. If anyone come across this, you can in the meantime do the following:

1. Add a file named `collect.d.ts` to your `src` or `src/types` folder (any folder that's read by `tsconfig.json` works) 
2. Paste the following content (we are doing declaration merging):  
```ts
declare module 'collect.js' {
  interface Collection<Item> {
    /**
     * The all method returns the underlying array represented by the collection.
     * Extended to support returning either Item[] or Object.
     */
    all(): Item[] | Record<unkown, Item>;
  }
}
```
3. When you call `.all()` you will have to cast the type, eg:  
```ts
type Contract = {
  'address': string;
  'abi': string;
}
const contracts = [
  {
    address: 'abc',
    abi: 'xyz',
  },
  {
    address: 'qwe',
    abi: 'asd',
  },
]
const contractsCollection = collect(contracts);
const keys = contractsCollection.mapWithKeys((contract: Contract) => [contract.address, contract.abi]);
const contractToAbiMap = keys.all() as Record<string, string>;
```

Ps: compared to the linked PR (#306) it's better to use `unkown` for the key type, since the key is not guaranteed to be a string.
